### ISSUE TITLE
Frames mod

### ISSUE THREAD

**Issue by Elon61** [RisingKingdom/Rising-Kingdom-1.7.10#16]
Can you add a 'frames' mod like [Funky Locomotion](https://minecraft.curseforge.com/projects/funky-locomotion)

**Comment by Rongmario** [comment]
There a couple options:

1. https://minecraft.curseforge.com/projects/framez
2. https://minecraft.curseforge.com/projects/funky-locomotion < like you said
3. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104611-remain-in-motion-continuation-of-redstone-in
4. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1444477-truss-mod-rp2-style-frames

**Comment by Rongmario** [comment]
Funky Lomotion was picked.
